In [2]:
# 1(a) Tensor Initialization and Data Types
%pip install torch
import torch

# 1D tensor
a = torch.tensor([1, 2, 3], dtype=torch.float32)
print(a)

# Zeros and Ones
zeros = torch.zeros((2, 3))
ones = torch.ones((3, 2))
print(zeros)
print(ones)

# Random tensor
rand = torch.rand((2, 2))
print(rand)

# Empty tensor
x = torch.empty(4, 2)
print(x)

# Linspace tensor
y = torch.linspace(0.1, 5, 15)
print(y)

# Identity Matrix
b = torch.eye(5, 5)
print(b)

# Arange tensor
c = torch.arange(8)
print(c)

# Normal distributed tensor
z = torch.empty(5, 12).normal_(mean=0, std=1)
print(z)

# Different data type conversion
tensor = torch.arange(10)
print(tensor.bool())   # Convert to boolean
print( tensor.short())   # Convert to int16
print(tensor.long())   # Convert to int64
print(tensor.half())   # Convert to float16
print(tensor.float())   # Convert to float32
print(tensor.double())   # Convert to float64



[notice] A new release of pip is available: 25.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip



   ---------------------------------------- 0.0/110.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/110.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/110.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/110.9 MB 799.2 kB/s eta 0:02:19
   ---------------------------------------- 0.5/110.9 MB 799.2 kB/s eta 0:02:19
   ---------------------------------------- 0.8/110.9 MB 763.2 kB/s eta 0:02:25
   ---------------------------------------- 1.0/110.9 MB 751.8 kB/s eta 0:02:27
   ---------------------------------------- 1.3/110.9 MB 818.6 kB/s eta 0:02:14
    --------------------------------------- 1.6/110.9 MB 932.2 kB/s eta 0:01:58
    --------------------------------------- 1.8/110.9 MB 959.1 kB/s eta 0:01:54
    --------------------------------------- 1.8/110.9 MB 959.1 kB/s eta 0:01:54
    --------------------------------------- 2.1/110.9 MB 903.5 kB/s eta 0:02:01
    --------------------------------------- 2.1/110.9 MB 903.5 kB/

In [3]:
# 1(b) Tensor Operations (Arithmetic, Broadcasting, Indexing, Reshaping)

x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Arithmetic operations
print(x + y)
print(x * y)
print(x - y)
print(x / y)

# Broadcasting
z = torch.tensor([10, 20])
print(x + z)

# Indexing
print(x[0])      # First row
print(x[:, 1])   # Second column

# Reshaping
a = torch.arange(6)
a = a.reshape(2, 3)
print(a)

tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[11, 22],
        [13, 24]])
tensor([1, 2])
tensor([2, 4])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [4]:
# 1(c) Automatic Differentiation using Autograd
a = torch.tensor(2.0, requires_grad=True)
b = a ** 2 + 3 * a + 1

b.backward()
print("Gradient:", a.grad)


Gradient: tensor(7.)
